name: Go CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.1'

      - name: Format
        run:
          files=$(gofmt -l .)
            if [ -n "$files" ]; then
                echo "The following files are not formatted:"
                echo "$files"
                exit 1
            fi

      - name: Static Analysis
        run: |
          echo "Running static analysis... TBD"

      - name: Build
        run: go build -v ./cmd/app